### PR TITLE
Update PlanningData-Form.xlsx

### PR DESCRIPTION
**Pull request by iridivm**
Hey,

Ik heb de letter C neergezet bij het tentamen van 2018.

Joel de Vries

### CODE REVIEW

**Comment by a-t-0** [comment]
Thank you, could you explain why you did not allocate yourself at question 3 of that exam?

**Comment by iridivm** [comment]
I did not allocate myself since that question is not part of the exam
material this year.

Kind regards

**Comment by a-t-0** [comment]
Thank you for your elaboration, that's good! Could you please fork/pull again from my master,  change your C to D and re-send me a pull request to solve a crosspost?

**Comment by iridivm** [comment]
Changed to letter D

**Comment by a-t-0** [comment]
Thank you for your quick adaptation. You did not pull from my master branch yet, which has an extra, conflicting commit. Please re-pull/fork from my master, then edit your letter :)

**Pull request closed without merging**
